/*
SQLyog Community v13.2.0 (64 bit)
MySQL - 10.4.24-MariaDB : Database - myappsec
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`myappsec` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `myappsec`;

/*Table structure for table `vapt` */

DROP TABLE IF EXISTS `vapt`;

CREATE TABLE `vapt` (
  `vapt_id` int(11) NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `assigned_to` int(11) DEFAULT NULL,
  `product_name` varchar(100) DEFAULT NULL,
  `assigned_date` date DEFAULT NULL,
  `last_updatedby` varchar(100) DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `delete_flag` tinyint(4) DEFAULT 0,
  `Test_Case_1` varchar(255) DEFAULT NULL,
  `Test_Case_2` text DEFAULT NULL,
  `Test_Case_3` text DEFAULT NULL,
  `Test_Case_4` text DEFAULT NULL,
  `Test_Case_5` text DEFAULT NULL,
  `Test_Case_6` text DEFAULT NULL,
  `Test_Case_7` text DEFAULT NULL,
  `Test_Case_8` text DEFAULT NULL,
  `Test_Case_9` text DEFAULT NULL,
  `Test_Case_10` text DEFAULT NULL,
  `Test_Case_11` text DEFAULT NULL,
  `Test_Case_12` text DEFAULT NULL,
  `Test_Case_13` text DEFAULT NULL,
  `Test_Case_14` text DEFAULT NULL,
  `Test_Case_15` text DEFAULT NULL,
  `Test_Case_16` text DEFAULT NULL,
  `Test_Case_17` text DEFAULT NULL,
  `Test_Case_18` text DEFAULT NULL,
  `Test_Case_19` text DEFAULT NULL,
  `Test_Case_20` text DEFAULT NULL,
  `Test_Case_21` text DEFAULT NULL,
  `Test_Case_22` text DEFAULT NULL,
  `Test_Case_23` text DEFAULT NULL,
  `Test_Case_24` text DEFAULT NULL,
  `Test_Case_25` text DEFAULT NULL,
  `Test_Case_26` text DEFAULT NULL,
  `Test_Case_27` text DEFAULT NULL,
  `Test_Case_28` text DEFAULT NULL,
  `Test_Case_29` text DEFAULT NULL,
  `Test_Case_30` text DEFAULT NULL,
  `Test_Case_31` text DEFAULT NULL,
  `Test_Case_32` text DEFAULT NULL,
  `Test_Case_33` text DEFAULT NULL,
  `Test_Case_34` text DEFAULT NULL,
  `Test_Case_35` text DEFAULT NULL,
  `Test_Case_36` text DEFAULT NULL,
  `Test_Case_37` text DEFAULT NULL,
  `Test_Case_38` text DEFAULT NULL,
  `Test_Case_39` text DEFAULT NULL,
  `Test_Case_40` text DEFAULT NULL,
  `Test_Case_41` text DEFAULT NULL,
  `Test_Case_42` text DEFAULT NULL,
  `Test_Case_43` text DEFAULT NULL,
  `Test_Case_44` text DEFAULT NULL,
  `Test_Case_45` text DEFAULT NULL,
  `Test_Case_46` text DEFAULT NULL,
  `Test_Case_47` text DEFAULT NULL,
  `Test_Case_48` text DEFAULT NULL,
  `Test_Case_49` text DEFAULT NULL,
  `Test_Case_50` text DEFAULT NULL,
  `Test_Case_51` text DEFAULT NULL,
  `Test_Case_52` text DEFAULT NULL,
  `Test_Case_53` text DEFAULT NULL,
  `Test_Case_54` text DEFAULT NULL,
  `Test_Case_55` text DEFAULT NULL,
  `Test_Case_56` text DEFAULT NULL,
  `Test_Case_57` text DEFAULT NULL,
  `Test_Case_58` text DEFAULT NULL,
  `Test_Case_59` text DEFAULT NULL,
  `Test_Case_60` text DEFAULT NULL,
  `Test_Case_61` text DEFAULT NULL,
  `Test_Case_62` text DEFAULT NULL,
  `Test_Case_63` text DEFAULT NULL,
  `Test_Case_64` text DEFAULT NULL,
  `Test_Case_65` text DEFAULT NULL,
  `Test_Case_66` text DEFAULT NULL,
  `Test_Case_67` text DEFAULT NULL,
  `Test_Case_68` text DEFAULT NULL,
  `Test_Case_69` text DEFAULT NULL,
  `Test_Case_70` text DEFAULT NULL,
  `Test_Case_71` text DEFAULT NULL,
  `Test_Case_72` text DEFAULT NULL,
  `Test_Case_73` text DEFAULT NULL,
  `Test_Case_74` text DEFAULT NULL,
  `Test_Case_75` text DEFAULT NULL,
  `Test_Case_76` text DEFAULT NULL,
  `Test_Case_77` text DEFAULT NULL,
  `Test_Case_78` text DEFAULT NULL,
  `Test_Case_79` text DEFAULT NULL,
  `Test_Case_80` text DEFAULT NULL,
  `Test_Case_81` text DEFAULT NULL,
  `Test_Case_82` text DEFAULT NULL,
  `Test_Case_83` text DEFAULT NULL,
  `Test_Case_84` text DEFAULT NULL,
  `Test_Case_85` text DEFAULT NULL,
  `Test_Case_86` text DEFAULT NULL,
  `Test_Case_87` text DEFAULT NULL,
  `Test_Case_88` text DEFAULT NULL,
  `Test_Case_89` text DEFAULT NULL,
  `manual_testing_Test_Case_1` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_2` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_3` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_4` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_5` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_6` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_7` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_8` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_9` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_10` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_11` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_12` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_13` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_14` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_15` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_16` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_17` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_18` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_19` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_20` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_21` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_22` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_23` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_24` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_25` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_26` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_27` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_28` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_29` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_30` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_31` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_32` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_33` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_34` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_35` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_36` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_37` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_38` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_39` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_40` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_41` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_42` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_43` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_44` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_45` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_46` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_47` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_48` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_49` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_50` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_51` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_52` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_53` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_54` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_55` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_56` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_57` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_58` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_59` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_60` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_61` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_62` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_63` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_64` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_65` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_66` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_67` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_68` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_69` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_70` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_71` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_72` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_73` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_74` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_75` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_76` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_77` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_78` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_79` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_80` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_81` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_82` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_83` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_84` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_85` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_86` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_87` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_88` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `manual_testing_Test_Case_89` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_1` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_2` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_3` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_4` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_5` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_6` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_7` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_8` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_9` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_10` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_11` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_12` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_13` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_14` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_15` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_16` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_17` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_18` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_19` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_20` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_21` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_22` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_23` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_24` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_25` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_26` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_27` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_28` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_29` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_30` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_31` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_32` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_33` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_34` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_35` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_36` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_37` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_38` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_39` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_40` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_41` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_42` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_43` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_44` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_45` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_46` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_47` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_48` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_49` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_50` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_51` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_52` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_53` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_54` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_55` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_56` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_57` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_58` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_59` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_60` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_61` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_62` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_63` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_64` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_65` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_66` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_67` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_68` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_69` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_70` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_71` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_72` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_73` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_74` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_75` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_76` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_77` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_78` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_79` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_80` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_81` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_82` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_83` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_84` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_85` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_86` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_87` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_88` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `code_review_Test_Case_89` enum('Not Started','In Progress','OnHold','Not Applicable','Completed') DEFAULT NULL,
  `notes_Test_Case_1` text DEFAULT NULL,
  `notes_Test_Case_2` text DEFAULT NULL,
  `notes_Test_Case_3` text DEFAULT NULL,
  `notes_Test_Case_4` text DEFAULT NULL,
  `notes_Test_Case_5` text DEFAULT NULL,
  `notes_Test_Case_6` text DEFAULT NULL,
  `notes_Test_Case_7` text DEFAULT NULL,
  `notes_Test_Case_8` text DEFAULT NULL,
  `notes_Test_Case_9` text DEFAULT NULL,
  `notes_Test_Case_10` text DEFAULT NULL,
  `notes_Test_Case_11` text DEFAULT NULL,
  `notes_Test_Case_12` text DEFAULT NULL,
  `notes_Test_Case_13` text DEFAULT NULL,
  `notes_Test_Case_14` text DEFAULT NULL,
  `notes_Test_Case_15` text DEFAULT NULL,
  `notes_Test_Case_16` text DEFAULT NULL,
  `notes_Test_Case_17` text DEFAULT NULL,
  `notes_Test_Case_18` text DEFAULT NULL,
  `notes_Test_Case_19` text DEFAULT NULL,
  `notes_Test_Case_20` text DEFAULT NULL,
  `notes_Test_Case_21` text DEFAULT NULL,
  `notes_Test_Case_22` text DEFAULT NULL,
  `notes_Test_Case_23` text DEFAULT NULL,
  `notes_Test_Case_24` text DEFAULT NULL,
  `notes_Test_Case_25` text DEFAULT NULL,
  `notes_Test_Case_26` text DEFAULT NULL,
  `notes_Test_Case_27` text DEFAULT NULL,
  `notes_Test_Case_28` text DEFAULT NULL,
  `notes_Test_Case_29` text DEFAULT NULL,
  `notes_Test_Case_30` text DEFAULT NULL,
  `notes_Test_Case_31` text DEFAULT NULL,
  `notes_Test_Case_32` text DEFAULT NULL,
  `notes_Test_Case_33` text DEFAULT NULL,
  `notes_Test_Case_34` text DEFAULT NULL,
  `notes_Test_Case_35` text DEFAULT NULL,
  `notes_Test_Case_36` text DEFAULT NULL,
  `notes_Test_Case_37` text DEFAULT NULL,
  `notes_Test_Case_38` text DEFAULT NULL,
  `notes_Test_Case_39` text DEFAULT NULL,
  `notes_Test_Case_40` text DEFAULT NULL,
  `notes_Test_Case_41` text DEFAULT NULL,
  `notes_Test_Case_42` text DEFAULT NULL,
  `notes_Test_Case_43` text DEFAULT NULL,
  `notes_Test_Case_44` text DEFAULT NULL,
  `notes_Test_Case_45` text DEFAULT NULL,
  `notes_Test_Case_46` text DEFAULT NULL,
  `notes_Test_Case_47` text DEFAULT NULL,
  `notes_Test_Case_48` text DEFAULT NULL,
  `notes_Test_Case_49` text DEFAULT NULL,
  `notes_Test_Case_50` text DEFAULT NULL,
  `notes_Test_Case_51` text DEFAULT NULL,
  `notes_Test_Case_52` text DEFAULT NULL,
  `notes_Test_Case_53` text DEFAULT NULL,
  `notes_Test_Case_54` text DEFAULT NULL,
  `notes_Test_Case_55` text DEFAULT NULL,
  `notes_Test_Case_56` text DEFAULT NULL,
  `notes_Test_Case_57` text DEFAULT NULL,
  `notes_Test_Case_58` text DEFAULT NULL,
  `notes_Test_Case_59` text DEFAULT NULL,
  `notes_Test_Case_60` text DEFAULT NULL,
  `notes_Test_Case_61` text DEFAULT NULL,
  `notes_Test_Case_62` text DEFAULT NULL,
  `notes_Test_Case_63` text DEFAULT NULL,
  `notes_Test_Case_64` text DEFAULT NULL,
  `notes_Test_Case_65` text DEFAULT NULL,
  `notes_Test_Case_66` text DEFAULT NULL,
  `notes_Test_Case_67` text DEFAULT NULL,
  `notes_Test_Case_68` text DEFAULT NULL,
  `notes_Test_Case_69` text DEFAULT NULL,
  `notes_Test_Case_70` text DEFAULT NULL,
  `notes_Test_Case_71` text DEFAULT NULL,
  `notes_Test_Case_72` text DEFAULT NULL,
  `notes_Test_Case_73` text DEFAULT NULL,
  `notes_Test_Case_74` text DEFAULT NULL,
  `notes_Test_Case_75` text DEFAULT NULL,
  `notes_Test_Case_76` text DEFAULT NULL,
  `notes_Test_Case_77` text DEFAULT NULL,
  `notes_Test_Case_78` text DEFAULT NULL,
  `notes_Test_Case_79` text DEFAULT NULL,
  `notes_Test_Case_80` text DEFAULT NULL,
  `notes_Test_Case_81` text DEFAULT NULL,
  `notes_Test_Case_82` text DEFAULT NULL,
  `notes_Test_Case_83` text DEFAULT NULL,
  `notes_Test_Case_84` text DEFAULT NULL,
  `notes_Test_Case_85` text DEFAULT NULL,
  `notes_Test_Case_86` text DEFAULT NULL,
  `notes_Test_Case_87` text DEFAULT NULL,
  `notes_Test_Case_88` text DEFAULT NULL,
  `notes_Test_Case_89` text DEFAULT NULL,
  `timetaken_Test_Case_1` int(3) DEFAULT NULL,
  `timetaken_Test_Case_2` int(3) DEFAULT NULL,
  `timetaken_Test_Case_3` int(3) DEFAULT NULL,
  `timetaken_Test_Case_4` int(3) DEFAULT NULL,
  `timetaken_Test_Case_5` int(3) DEFAULT NULL,
  `timetaken_Test_Case_6` int(3) DEFAULT NULL,
  `timetaken_Test_Case_7` int(3) DEFAULT NULL,
  `timetaken_Test_Case_8` int(3) DEFAULT NULL,
  `timetaken_Test_Case_9` int(3) DEFAULT NULL,
  `timetaken_Test_Case_10` int(3) DEFAULT NULL,
  `timetaken_Test_Case_11` int(3) DEFAULT NULL,
  `timetaken_Test_Case_12` int(3) DEFAULT NULL,
  `timetaken_Test_Case_13` int(3) DEFAULT NULL,
  `timetaken_Test_Case_14` int(3) DEFAULT NULL,
  `timetaken_Test_Case_15` int(3) DEFAULT NULL,
  `timetaken_Test_Case_16` int(3) DEFAULT NULL,
  `timetaken_Test_Case_17` int(3) DEFAULT NULL,
  `timetaken_Test_Case_18` int(3) DEFAULT NULL,
  `timetaken_Test_Case_19` int(3) DEFAULT NULL,
  `timetaken_Test_Case_20` int(3) DEFAULT NULL,
  `timetaken_Test_Case_21` int(3) DEFAULT NULL,
  `timetaken_Test_Case_22` int(3) DEFAULT NULL,
  `timetaken_Test_Case_23` int(3) DEFAULT NULL,
  `timetaken_Test_Case_24` int(3) DEFAULT NULL,
  `timetaken_Test_Case_25` int(3) DEFAULT NULL,
  `timetaken_Test_Case_26` int(3) DEFAULT NULL,
  `timetaken_Test_Case_27` int(3) DEFAULT NULL,
  `timetaken_Test_Case_28` int(3) DEFAULT NULL,
  `timetaken_Test_Case_29` int(3) DEFAULT NULL,
  `timetaken_Test_Case_30` int(3) DEFAULT NULL,
  `timetaken_Test_Case_31` int(3) DEFAULT NULL,
  `timetaken_Test_Case_32` int(3) DEFAULT NULL,
  `timetaken_Test_Case_33` int(3) DEFAULT NULL,
  `timetaken_Test_Case_34` int(3) DEFAULT NULL,
  `timetaken_Test_Case_35` int(3) DEFAULT NULL,
  `timetaken_Test_Case_36` int(3) DEFAULT NULL,
  `timetaken_Test_Case_37` int(3) DEFAULT NULL,
  `timetaken_Test_Case_38` int(3) DEFAULT NULL,
  `timetaken_Test_Case_39` int(3) DEFAULT NULL,
  `timetaken_Test_Case_40` int(3) DEFAULT NULL,
  `timetaken_Test_Case_41` int(3) DEFAULT NULL,
  `timetaken_Test_Case_42` int(3) DEFAULT NULL,
  `timetaken_Test_Case_43` int(3) DEFAULT NULL,
  `timetaken_Test_Case_44` int(3) DEFAULT NULL,
  `timetaken_Test_Case_45` int(3) DEFAULT NULL,
  `timetaken_Test_Case_46` int(3) DEFAULT NULL,
  `timetaken_Test_Case_47` int(3) DEFAULT NULL,
  `timetaken_Test_Case_48` int(3) DEFAULT NULL,
  `timetaken_Test_Case_49` int(3) DEFAULT NULL,
  `timetaken_Test_Case_50` int(3) DEFAULT NULL,
  `timetaken_Test_Case_51` int(3) DEFAULT NULL,
  `timetaken_Test_Case_52` int(3) DEFAULT NULL,
  `timetaken_Test_Case_53` int(3) DEFAULT NULL,
  `timetaken_Test_Case_54` int(3) DEFAULT NULL,
  `timetaken_Test_Case_55` int(3) DEFAULT NULL,
  `timetaken_Test_Case_56` int(3) DEFAULT NULL,
  `timetaken_Test_Case_57` int(3) DEFAULT NULL,
  `timetaken_Test_Case_58` int(3) DEFAULT NULL,
  `timetaken_Test_Case_59` int(3) DEFAULT NULL,
  `timetaken_Test_Case_60` int(3) DEFAULT NULL,
  `timetaken_Test_Case_61` int(3) DEFAULT NULL,
  `timetaken_Test_Case_62` int(3) DEFAULT NULL,
  `timetaken_Test_Case_63` int(3) DEFAULT NULL,
  `timetaken_Test_Case_64` int(3) DEFAULT NULL,
  `timetaken_Test_Case_65` int(3) DEFAULT NULL,
  `timetaken_Test_Case_66` int(3) DEFAULT NULL,
  `timetaken_Test_Case_67` int(3) DEFAULT NULL,
  `timetaken_Test_Case_68` int(3) DEFAULT NULL,
  `timetaken_Test_Case_69` int(3) DEFAULT NULL,
  `timetaken_Test_Case_70` int(3) DEFAULT NULL,
  `timetaken_Test_Case_71` int(3) DEFAULT NULL,
  `timetaken_Test_Case_72` int(3) DEFAULT NULL,
  `timetaken_Test_Case_73` int(3) DEFAULT NULL,
  `timetaken_Test_Case_74` int(3) DEFAULT NULL,
  `timetaken_Test_Case_75` int(3) DEFAULT NULL,
  `timetaken_Test_Case_76` int(3) DEFAULT NULL,
  `timetaken_Test_Case_77` int(3) DEFAULT NULL,
  `timetaken_Test_Case_78` int(3) DEFAULT NULL,
  `timetaken_Test_Case_79` int(3) DEFAULT NULL,
  `timetaken_Test_Case_80` int(3) DEFAULT NULL,
  `timetaken_Test_Case_81` int(3) DEFAULT NULL,
  `timetaken_Test_Case_82` int(3) DEFAULT NULL,
  `timetaken_Test_Case_83` int(3) DEFAULT NULL,
  `timetaken_Test_Case_84` int(3) DEFAULT NULL,
  `timetaken_Test_Case_85` int(3) DEFAULT NULL,
  `timetaken_Test_Case_86` int(3) DEFAULT NULL,
  `timetaken_Test_Case_87` int(3) DEFAULT NULL,
  `timetaken_Test_Case_88` int(3) DEFAULT NULL,
  `timetaken_Test_Case_89` int(3) DEFAULT NULL,
  PRIMARY KEY (`vapt_id`),
  KEY `assignment_id` (`assignment_id`),
  CONSTRAINT `vapt_ibfk_1` FOREIGN KEY (`assignment_id`) REFERENCES `assignments_vapt` (`assignment_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

/*Data for the table `vapt` */

insert  into `vapt`(`vapt_id`,`assignment_id`,`title`,`description`,`assigned_to`,`product_name`,`assigned_date`,`last_updatedby`,`timestamp`,`delete_flag`,`Test_Case_1`,`Test_Case_2`,`Test_Case_3`,`Test_Case_4`,`Test_Case_5`,`Test_Case_6`,`Test_Case_7`,`Test_Case_8`,`Test_Case_9`,`Test_Case_10`,`Test_Case_11`,`Test_Case_12`,`Test_Case_13`,`Test_Case_14`,`Test_Case_15`,`Test_Case_16`,`Test_Case_17`,`Test_Case_18`,`Test_Case_19`,`Test_Case_20`,`Test_Case_21`,`Test_Case_22`,`Test_Case_23`,`Test_Case_24`,`Test_Case_25`,`Test_Case_26`,`Test_Case_27`,`Test_Case_28`,`Test_Case_29`,`Test_Case_30`,`Test_Case_31`,`Test_Case_32`,`Test_Case_33`,`Test_Case_34`,`Test_Case_35`,`Test_Case_36`,`Test_Case_37`,`Test_Case_38`,`Test_Case_39`,`Test_Case_40`,`Test_Case_41`,`Test_Case_42`,`Test_Case_43`,`Test_Case_44`,`Test_Case_45`,`Test_Case_46`,`Test_Case_47`,`Test_Case_48`,`Test_Case_49`,`Test_Case_50`,`Test_Case_51`,`Test_Case_52`,`Test_Case_53`,`Test_Case_54`,`Test_Case_55`,`Test_Case_56`,`Test_Case_57`,`Test_Case_58`,`Test_Case_59`,`Test_Case_60`,`Test_Case_61`,`Test_Case_62`,`Test_Case_63`,`Test_Case_64`,`Test_Case_65`,`Test_Case_66`,`Test_Case_67`,`Test_Case_68`,`Test_Case_69`,`Test_Case_70`,`Test_Case_71`,`Test_Case_72`,`Test_Case_73`,`Test_Case_74`,`Test_Case_75`,`Test_Case_76`,`Test_Case_77`,`Test_Case_78`,`Test_Case_79`,`Test_Case_80`,`Test_Case_81`,`Test_Case_82`,`Test_Case_83`,`Test_Case_84`,`Test_Case_85`,`Test_Case_86`,`Test_Case_87`,`Test_Case_88`,`Test_Case_89`,`manual_testing_Test_Case_1`,`manual_testing_Test_Case_2`,`manual_testing_Test_Case_3`,`manual_testing_Test_Case_4`,`manual_testing_Test_Case_5`,`manual_testing_Test_Case_6`,`manual_testing_Test_Case_7`,`manual_testing_Test_Case_8`,`manual_testing_Test_Case_9`,`manual_testing_Test_Case_10`,`manual_testing_Test_Case_11`,`manual_testing_Test_Case_12`,`manual_testing_Test_Case_13`,`manual_testing_Test_Case_14`,`manual_testing_Test_Case_15`,`manual_testing_Test_Case_16`,`manual_testing_Test_Case_17`,`manual_testing_Test_Case_18`,`manual_testing_Test_Case_19`,`manual_testing_Test_Case_20`,`manual_testing_Test_Case_21`,`manual_testing_Test_Case_22`,`manual_testing_Test_Case_23`,`manual_testing_Test_Case_24`,`manual_testing_Test_Case_25`,`manual_testing_Test_Case_26`,`manual_testing_Test_Case_27`,`manual_testing_Test_Case_28`,`manual_testing_Test_Case_29`,`manual_testing_Test_Case_30`,`manual_testing_Test_Case_31`,`manual_testing_Test_Case_32`,`manual_testing_Test_Case_33`,`manual_testing_Test_Case_34`,`manual_testing_Test_Case_35`,`manual_testing_Test_Case_36`,`manual_testing_Test_Case_37`,`manual_testing_Test_Case_38`,`manual_testing_Test_Case_39`,`manual_testing_Test_Case_40`,`manual_testing_Test_Case_41`,`manual_testing_Test_Case_42`,`manual_testing_Test_Case_43`,`manual_testing_Test_Case_44`,`manual_testing_Test_Case_45`,`manual_testing_Test_Case_46`,`manual_testing_Test_Case_47`,`manual_testing_Test_Case_48`,`manual_testing_Test_Case_49`,`manual_testing_Test_Case_50`,`manual_testing_Test_Case_51`,`manual_testing_Test_Case_52`,`manual_testing_Test_Case_53`,`manual_testing_Test_Case_54`,`manual_testing_Test_Case_55`,`manual_testing_Test_Case_56`,`manual_testing_Test_Case_57`,`manual_testing_Test_Case_58`,`manual_testing_Test_Case_59`,`manual_testing_Test_Case_60`,`manual_testing_Test_Case_61`,`manual_testing_Test_Case_62`,`manual_testing_Test_Case_63`,`manual_testing_Test_Case_64`,`manual_testing_Test_Case_65`,`manual_testing_Test_Case_66`,`manual_testing_Test_Case_67`,`manual_testing_Test_Case_68`,`manual_testing_Test_Case_69`,`manual_testing_Test_Case_70`,`manual_testing_Test_Case_71`,`manual_testing_Test_Case_72`,`manual_testing_Test_Case_73`,`manual_testing_Test_Case_74`,`manual_testing_Test_Case_75`,`manual_testing_Test_Case_76`,`manual_testing_Test_Case_77`,`manual_testing_Test_Case_78`,`manual_testing_Test_Case_79`,`manual_testing_Test_Case_80`,`manual_testing_Test_Case_81`,`manual_testing_Test_Case_82`,`manual_testing_Test_Case_83`,`manual_testing_Test_Case_84`,`manual_testing_Test_Case_85`,`manual_testing_Test_Case_86`,`manual_testing_Test_Case_87`,`manual_testing_Test_Case_88`,`manual_testing_Test_Case_89`,`code_review_Test_Case_1`,`code_review_Test_Case_2`,`code_review_Test_Case_3`,`code_review_Test_Case_4`,`code_review_Test_Case_5`,`code_review_Test_Case_6`,`code_review_Test_Case_7`,`code_review_Test_Case_8`,`code_review_Test_Case_9`,`code_review_Test_Case_10`,`code_review_Test_Case_11`,`code_review_Test_Case_12`,`code_review_Test_Case_13`,`code_review_Test_Case_14`,`code_review_Test_Case_15`,`code_review_Test_Case_16`,`code_review_Test_Case_17`,`code_review_Test_Case_18`,`code_review_Test_Case_19`,`code_review_Test_Case_20`,`code_review_Test_Case_21`,`code_review_Test_Case_22`,`code_review_Test_Case_23`,`code_review_Test_Case_24`,`code_review_Test_Case_25`,`code_review_Test_Case_26`,`code_review_Test_Case_27`,`code_review_Test_Case_28`,`code_review_Test_Case_29`,`code_review_Test_Case_30`,`code_review_Test_Case_31`,`code_review_Test_Case_32`,`code_review_Test_Case_33`,`code_review_Test_Case_34`,`code_review_Test_Case_35`,`code_review_Test_Case_36`,`code_review_Test_Case_37`,`code_review_Test_Case_38`,`code_review_Test_Case_39`,`code_review_Test_Case_40`,`code_review_Test_Case_41`,`code_review_Test_Case_42`,`code_review_Test_Case_43`,`code_review_Test_Case_44`,`code_review_Test_Case_45`,`code_review_Test_Case_46`,`code_review_Test_Case_47`,`code_review_Test_Case_48`,`code_review_Test_Case_49`,`code_review_Test_Case_50`,`code_review_Test_Case_51`,`code_review_Test_Case_52`,`code_review_Test_Case_53`,`code_review_Test_Case_54`,`code_review_Test_Case_55`,`code_review_Test_Case_56`,`code_review_Test_Case_57`,`code_review_Test_Case_58`,`code_review_Test_Case_59`,`code_review_Test_Case_60`,`code_review_Test_Case_61`,`code_review_Test_Case_62`,`code_review_Test_Case_63`,`code_review_Test_Case_64`,`code_review_Test_Case_65`,`code_review_Test_Case_66`,`code_review_Test_Case_67`,`code_review_Test_Case_68`,`code_review_Test_Case_69`,`code_review_Test_Case_70`,`code_review_Test_Case_71`,`code_review_Test_Case_72`,`code_review_Test_Case_73`,`code_review_Test_Case_74`,`code_review_Test_Case_75`,`code_review_Test_Case_76`,`code_review_Test_Case_77`,`code_review_Test_Case_78`,`code_review_Test_Case_79`,`code_review_Test_Case_80`,`code_review_Test_Case_81`,`code_review_Test_Case_82`,`code_review_Test_Case_83`,`code_review_Test_Case_84`,`code_review_Test_Case_85`,`code_review_Test_Case_86`,`code_review_Test_Case_87`,`code_review_Test_Case_88`,`code_review_Test_Case_89`,`notes_Test_Case_1`,`notes_Test_Case_2`,`notes_Test_Case_3`,`notes_Test_Case_4`,`notes_Test_Case_5`,`notes_Test_Case_6`,`notes_Test_Case_7`,`notes_Test_Case_8`,`notes_Test_Case_9`,`notes_Test_Case_10`,`notes_Test_Case_11`,`notes_Test_Case_12`,`notes_Test_Case_13`,`notes_Test_Case_14`,`notes_Test_Case_15`,`notes_Test_Case_16`,`notes_Test_Case_17`,`notes_Test_Case_18`,`notes_Test_Case_19`,`notes_Test_Case_20`,`notes_Test_Case_21`,`notes_Test_Case_22`,`notes_Test_Case_23`,`notes_Test_Case_24`,`notes_Test_Case_25`,`notes_Test_Case_26`,`notes_Test_Case_27`,`notes_Test_Case_28`,`notes_Test_Case_29`,`notes_Test_Case_30`,`notes_Test_Case_31`,`notes_Test_Case_32`,`notes_Test_Case_33`,`notes_Test_Case_34`,`notes_Test_Case_35`,`notes_Test_Case_36`,`notes_Test_Case_37`,`notes_Test_Case_38`,`notes_Test_Case_39`,`notes_Test_Case_40`,`notes_Test_Case_41`,`notes_Test_Case_42`,`notes_Test_Case_43`,`notes_Test_Case_44`,`notes_Test_Case_45`,`notes_Test_Case_46`,`notes_Test_Case_47`,`notes_Test_Case_48`,`notes_Test_Case_49`,`notes_Test_Case_50`,`notes_Test_Case_51`,`notes_Test_Case_52`,`notes_Test_Case_53`,`notes_Test_Case_54`,`notes_Test_Case_55`,`notes_Test_Case_56`,`notes_Test_Case_57`,`notes_Test_Case_58`,`notes_Test_Case_59`,`notes_Test_Case_60`,`notes_Test_Case_61`,`notes_Test_Case_62`,`notes_Test_Case_63`,`notes_Test_Case_64`,`notes_Test_Case_65`,`notes_Test_Case_66`,`notes_Test_Case_67`,`notes_Test_Case_68`,`notes_Test_Case_69`,`notes_Test_Case_70`,`notes_Test_Case_71`,`notes_Test_Case_72`,`notes_Test_Case_73`,`notes_Test_Case_74`,`notes_Test_Case_75`,`notes_Test_Case_76`,`notes_Test_Case_77`,`notes_Test_Case_78`,`notes_Test_Case_79`,`notes_Test_Case_80`,`notes_Test_Case_81`,`notes_Test_Case_82`,`notes_Test_Case_83`,`notes_Test_Case_84`,`notes_Test_Case_85`,`notes_Test_Case_86`,`notes_Test_Case_87`,`notes_Test_Case_88`,`notes_Test_Case_89`,`timetaken_Test_Case_1`,`timetaken_Test_Case_2`,`timetaken_Test_Case_3`,`timetaken_Test_Case_4`,`timetaken_Test_Case_5`,`timetaken_Test_Case_6`,`timetaken_Test_Case_7`,`timetaken_Test_Case_8`,`timetaken_Test_Case_9`,`timetaken_Test_Case_10`,`timetaken_Test_Case_11`,`timetaken_Test_Case_12`,`timetaken_Test_Case_13`,`timetaken_Test_Case_14`,`timetaken_Test_Case_15`,`timetaken_Test_Case_16`,`timetaken_Test_Case_17`,`timetaken_Test_Case_18`,`timetaken_Test_Case_19`,`timetaken_Test_Case_20`,`timetaken_Test_Case_21`,`timetaken_Test_Case_22`,`timetaken_Test_Case_23`,`timetaken_Test_Case_24`,`timetaken_Test_Case_25`,`timetaken_Test_Case_26`,`timetaken_Test_Case_27`,`timetaken_Test_Case_28`,`timetaken_Test_Case_29`,`timetaken_Test_Case_30`,`timetaken_Test_Case_31`,`timetaken_Test_Case_32`,`timetaken_Test_Case_33`,`timetaken_Test_Case_34`,`timetaken_Test_Case_35`,`timetaken_Test_Case_36`,`timetaken_Test_Case_37`,`timetaken_Test_Case_38`,`timetaken_Test_Case_39`,`timetaken_Test_Case_40`,`timetaken_Test_Case_41`,`timetaken_Test_Case_42`,`timetaken_Test_Case_43`,`timetaken_Test_Case_44`,`timetaken_Test_Case_45`,`timetaken_Test_Case_46`,`timetaken_Test_Case_47`,`timetaken_Test_Case_48`,`timetaken_Test_Case_49`,`timetaken_Test_Case_50`,`timetaken_Test_Case_51`,`timetaken_Test_Case_52`,`timetaken_Test_Case_53`,`timetaken_Test_Case_54`,`timetaken_Test_Case_55`,`timetaken_Test_Case_56`,`timetaken_Test_Case_57`,`timetaken_Test_Case_58`,`timetaken_Test_Case_59`,`timetaken_Test_Case_60`,`timetaken_Test_Case_61`,`timetaken_Test_Case_62`,`timetaken_Test_Case_63`,`timetaken_Test_Case_64`,`timetaken_Test_Case_65`,`timetaken_Test_Case_66`,`timetaken_Test_Case_67`,`timetaken_Test_Case_68`,`timetaken_Test_Case_69`,`timetaken_Test_Case_70`,`timetaken_Test_Case_71`,`timetaken_Test_Case_72`,`timetaken_Test_Case_73`,`timetaken_Test_Case_74`,`timetaken_Test_Case_75`,`timetaken_Test_Case_76`,`timetaken_Test_Case_77`,`timetaken_Test_Case_78`,`timetaken_Test_Case_79`,`timetaken_Test_Case_80`,`timetaken_Test_Case_81`,`timetaken_Test_Case_82`,`timetaken_Test_Case_83`,`timetaken_Test_Case_84`,`timetaken_Test_Case_85`,`timetaken_Test_Case_86`,`timetaken_Test_Case_87`,`timetaken_Test_Case_88`,`timetaken_Test_Case_89`) values 
(1,15,'trimm',NULL,NULL,NULL,NULL,NULL,'2024-04-23 09:20:54',0,'Information Gathering: OTG-INFO-001 - Conduct Search Engine Discovery and Reconnaissance for Information Leakage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/* Trigger structure for table `assignments` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `after_assignment_insert` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `after_assignment_insert` AFTER INSERT ON `assignments` FOR EACH ROW 
BEGIN
    INSERT INTO patches (assignment_id, title, description, assigned_to, product_name, assigned_date)
    VALUES (NEW.assignment_id, NEW.title, NEW.description, NEW.assigned_to, NEW.product_name, NEW.assigned_date);
END */$$


DELIMITER ;

/* Trigger structure for table `assignments` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `after_assignment_insert1` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `after_assignment_insert1` AFTER INSERT ON `assignments` FOR EACH ROW 
BEGIN
    INSERT INTO summary (assignment_id) VALUES (NEW.assignment_id);
END */$$


DELIMITER ;

/* Trigger structure for table `assignments` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `insert_into_patches` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `insert_into_patches` AFTER INSERT ON `assignments` FOR EACH ROW 
BEGIN
    IF NEW.rm_pm IS NOT NULL THEN
        INSERT INTO patches (assignment_id, rm_pm)
        VALUES (NEW.assignment_id, NEW.rm_pm);
    END IF;
END */$$


DELIMITER ;

/* Trigger structure for table `assignments_vapt` */

DELIMITER $$

/*!50003 DROP TRIGGER*//*!50032 IF EXISTS */ /*!50003 `after_insert_assignments_vapt` */$$

/*!50003 CREATE */ /*!50017 DEFINER = 'root'@'localhost' */ /*!50003 TRIGGER `after_insert_assignments_vapt` AFTER INSERT ON `assignments_vapt` FOR EACH ROW 
BEGIN
    DECLARE v_assigned_to VARCHAR(255);
    DECLARE v_description TEXT;
    DECLARE v_product_name VARCHAR(100);
    
    -- Get assigned_to, description, and product_name from assignments table based on assignment_id
    SELECT CONCAT(u.ufname, ' ', u.ulname), a.description, a.product_name 
    INTO v_assigned_to, v_description, v_product_name
    FROM users u 
    JOIN assignments a ON u.user_id = a.assigned_to 
    WHERE a.assignment_id = NEW.assignment_id;

    -- Insert values into vapt table
    INSERT INTO vapt (assignment_id, title, description, assigned_to, product_name)
    VALUES (NEW.assignment_id, NEW.title, v_description, v_assigned_to, v_product_name);
END */$$


DELIMITER ;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
